server:
  port: 8080

spring:
  application:
    name: anime-service

  # C?u hình Database
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/myanimelist_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # C?u hình JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Format câu SQL cho ??p m?t khi log
        dialect: org.hibernate.dialect.MySQLDialect

  # C?u hình Upload File (T?ng dung l??ng)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# C?u hình riêng c?a App (Custom)
jwt:
  signerKey: ${JWT_SIGNER_KEY:12345678901234gdfgd567890123456789012}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:kurisu}
  api-key: ${CLOUDINARY_API_KEY:4124324}
  api-secret: ${CLOUDINARY_API_SECRET}
# Khóa bí m?t dùng ?? ký token (Tuy?t ??i không l? ra ngoài)
# ?ây là chu?i random, b?n có th? gõ b?a 1 ?o?n dài ngo?ng là ???c
